=== GetFire/TTTM_dev/config/competition.dtd
<?xml version='1.0' encoding='ISO-8859-1' ?>

<!ELEMENT competition (tableau_simple+, tableau_poules+) >
<!ATTLIST competition
   nombre_tables CDATA #REQUIRED   
>
<!ELEMENT tableau_simple (deroulement*) >
<!ATTLIST tableau_simple
   nom ID #REQUIRED
   type (KO|doubleKO|intégrale) #REQUIRED
   max_joueurs CDATA #REQUIRED
   min_joueurs CDATA "1"
   visible (oui|non) "oui"
>
<!ELEMENT deroulement (ordre_match)>
<!ELEMENT ordre_match (match+)>
<!ELEMENT match EMPTY>
<!ATTLIST match
   numero CDATA #REQUIRED
   adversaire1 CDATA #REQUIRED
   adversaire2 CDATA #REQUIRED
>
<!ELEMENT tableau_poules (poules, classement_poules*, sortie_poule+) >
<!ATTLIST tableau_poules
   nom ID #REQUIRED
   visible (oui|non) "oui"
>
<!ELEMENT poules EMPTY>
<!ATTLIST poules
   nombre CDATA #REQUIRED
   nombre_joueurs CDATA #REQUIRED
>
<!ELEMENT classement_poules EMPTY>
<!ATTLIST classement_poules
   poule CDATA #REQUIRED
   joueur CDATA #REQUIRED
   classement CDATA #REQUIRED
>
<!ELEMENT sortie_poule EMPTY>
<!ATTLIST sortie_poule   
   nombre_joueurs CDATA #REQUIRED   
   ref_tableau IDREF #REQUIRED
   nom_tableau CDATA #REQUIRED
>

=== GetFire/TTTM_dev/config/competition.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no' ?>    
<!-- fichier competition.xml --> 
<!DOCTYPE competition SYSTEM "competition.dtd"[
]> 
<competition nombre_tables="16">
  <tableau_simple nom="tab4KO" max_joueurs="4" type="KO" visible="non">   
    <deroulement>
      <ordre_match>
        <match numero="1" adversaire1="1" adversaire2="4"/>
        <match numero="2" adversaire1="2" adversaire2="3"/>
      </ordre_match>
    </deroulement>
  </tableau_simple>
  <tableau_poules nom="tab32DoubleKOPoule4" visible="non">
    <poules nombre="8" nombre_joueurs="4" />
    <sortie_poule nombre_joueurs="4" ref_tableau="tab4KO" nom_tableau="principal"/>
  </tableau_poules>
</competition>
